In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import warnings
warnings.filterwarnings('ignore')

In [4]:
A = [[6, 9, 2],
     [3, 3, 7],
     [1, 0, 3]]

A_tensor = torch.tensor(A)
A_tensor

tensor([[6, 9, 2],
        [3, 3, 7],
        [1, 0, 3]])

In [5]:
B = np.array([0, 1, 2, 3])
B_tensor = torch.tensor(B)
B_tensor

tensor([0, 1, 2, 3])

In [6]:
# with no dtype argument, torch will infer the type
C = torch.zeros(4, 4)
C

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
D = torch.ones(3, 3, 2, dtype=torch.int)
D

tensor([[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]], dtype=torch.int32)

In [8]:
A_tensor_zeros = torch.zeros_like(A_tensor)

A_tensor_zeros

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
# the dtype argument allows you to explicitlt specify the datatype of the tensor
A_tensor_rand = torch.rand_like(A_tensor, dtype=torch.float)

A_tensor_rand

tensor([[0.3719, 0.1128, 0.0813],
        [0.8178, 0.7547, 0.7966],
        [0.6341, 0.5430, 0.6523]])

In [12]:
A_tensor_rand.dtype
# torch.float32

A_tensor_rand.shape
# torch.Size([3, 3])

A_tensor_rand.device
# device(type='cpu')

device(type='cpu')

## Conclusion:
    
Creating tensors is fine, but the real fun starts when we can start manipulating them and applying mathematical operations. There are a ton of neat tensor operations already built-in, so we certainly won’t have time to go through them all. Instead, here is a link to check [them out in further detail](https://pytorch.org/docs/stable/torch.html), and just name a few:

- matrix multiplication
- compute eigenvectors and eigenvalues
- sorting
- index,slice,join
- hamming window 