<a href="https://colab.research.google.com/github/aurimas13/CodeAcademy-AI-Course/blob/main/Examples/Example_with_OneHotEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

In [ ]:
ids = [1,2,3,4,5,6]
fruits = ['Strawberry', 'Apple', 'Watermelon', 'Lemon', 'Peach', 'Orange']
df = pd.DataFrame(list(zip(ids, fruits)), columns=['Ids', 'Fruits'])

In [ ]:
df.head()

Ids      Fruits
0    1  Strawberry
1    2       Apple
2    3  Watermelon
3    4       Lemon
4    5       Peach

### <i> Becasue Fruits column contain categorical values, we may convert the values in the Fruits column into one-hot encoded vectors using the get_dummies() function:

In [ ]:
y = pd.get_dummies(df.Fruits, prefix='Fruits')
print(y.head())

   Fruits_Apple  Fruits_Lemon  Fruits_Orange  Fruits_Peach  Fruits_Strawberry  \
0             0             0              0             0                  1   
1             1             0              0             0                  0   
2             0             0              0             0                  0   
3             0             1              0             0                  0   
4             0             0              0             1                  0   

   Fruits_Watermelon  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  


# <b>Alternative way</b>

In [ ]:
from sklearn.preprocessing import OneHotEncoder

And then, let's populate a list and fit it in the encoder:

In [ ]:
x = [[1, 'Strawberry'], [2, 'Apple'], [3, 'Watermelon'], [4, 'Lemon'], [5, 'Peach'], (6, 'Orange')]
y = OneHotEncoder().fit_transform(x).toarray()
print(y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]]
